# Generated by Django 3.0.5 on 2020-06-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
