# Generated by Django 3.0.5 on 2020-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0002_auto_20200618_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='logtable',
            name='macAddress',
            field=models.CharField(max_length=20),
        ),
    ]
