# Generated by Django 3.0.2 on 2020-05-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0003_auto_20200511_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
