# Generated by Django 3.0.2 on 2020-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0004_auto_20200511_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
