# Generated by Django 3.0.2 on 2020-05-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0005_auto_20200511_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=30)),
                ('lecture_room', models.CharField(max_length=7)),
                ('department', models.CharField(max_length=20)),
                ('lecture_id', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(default='정보보호학과', max_length=20),
        ),
        migrations.CreateModel(
            name='Subject_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=5)),
                ('which_day', models.CharField(max_length=8)),
                ('start_time', models.CharField(max_length=8)),
                ('finish_time', models.CharField(max_length=8)),
                ('Subject_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberauth.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Member_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=8)),
                ('Member_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberauth.Member')),
            ],
        ),
    ]
