# Generated by Django 3.0.2 on 2020-05-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0006_auto_20200512_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_course',
            name='Member_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_id', to='memberauth.Member'),
        ),
    ]
