# Generated by Django 3.0.2 on 2020-06-08 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0007_auto_20200512_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade_number', models.CharField(max_length=10, unique=True)),
                ('mac_address', models.CharField(max_length=20)),
                ('department', models.CharField(default='기타', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(default='기타', max_length=20),
        ),
        migrations.AlterField(
            model_name='member_course',
            name='Member_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberauth.Member'),
        ),
        migrations.AlterField(
            model_name='subject_time',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='ProMember_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=8)),
                ('ProMember_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberauth.Member')),
            ],
        ),
    ]
