# Generated by Django 3.0.5 on 2020-05-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0007_auto_20200512_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_course',
            name='Member_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberauth.Member'),
        ),
        migrations.AlterField(
            model_name='subject_time',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
