# Generated by Django 3.0.5 on 2020-06-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0008_auto_20200521_0833'),
        ('memberauth', '0008_auto_20200608_2040'),
    ]

    operations = [
    ]
