# Generated by Django 3.0.2 on 2020-06-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0009_auto_20200612_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('num', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('mac_addr', models.CharField(max_length=12)),
                ('lecture_room', models.CharField(max_length=7)),
                ('pwr', models.IntegerField()),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
