# Generated by Django 3.0.5 on 2020-06-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0009_auto_20200612_1639'),
        ('memberauth', '0009_merge_20200608_1300'),
    ]

    operations = [
    ]
