# Generated by Django 3.0.2 on 2020-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0010_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='count',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='pwr',
            field=models.IntegerField(max_length=1),
        ),
    ]
