# Generated by Django 3.0.2 on 2020-06-13 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0011_auto_20200613_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='pwr',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
