# Generated by Django 3.0.5 on 2020-06-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0012_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
