# Generated by Django 3.0.2 on 2020-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0013_auto_20200613_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
