# Generated by Django 3.0.5 on 2020-06-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0013_auto_20200614_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='wifilog',
        ),
        migrations.AlterModelTable(
            name='wifilog',
            table=None,
        ),
    ]
