# Generated by Django 3.0.5 on 2020-06-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0014_auto_20200614_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='wifilog',
        ),
    ]
