# Generated by Django 3.0.5 on 2020-06-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0015_auto_20200614_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('mac_addr', models.CharField(max_length=12)),
                ('lecture_room', models.CharField(max_length=7)),
                ('pwr', models.IntegerField()),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Log',
                'managed': False,
            },
        ),
    ]
