# Generated by Django 3.0.2 on 2020-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0015_auto_20200613_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
