# Generated by Django 3.0.2 on 2020-06-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0020_auto_20200613_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(blank=True, default=0, editable=False, null=True),
        ),
    ]
