# Generated by Django 3.0.2 on 2020-06-13 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0025_auto_20200613_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 6, 8, 5, 183859, tzinfo=utc)),
        ),
    ]
