# Generated by Django 3.0.2 on 2020-06-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0027_auto_20200613_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
    ]
