# Generated by Django 3.0.2 on 2020-06-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0028_remove_log_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
    ]
