# Generated by Django 3.0.2 on 2020-06-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0029_auto_20200614_1505'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='log',
            table='Log',
        ),
    ]
