# Generated by Django 3.0.2 on 2020-06-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0030_auto_20200614_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
