# Generated by Django 3.0.2 on 2020-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0032_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='promember',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
