# Generated by Django 3.0.2 on 2020-06-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0035_delete_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logTable',
        ),
    ]
