# Generated by Django 3.0.2 on 2020-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0037_logtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('mac_addr', models.CharField(max_length=12)),
                ('lecture_room', models.CharField(max_length=7)),
                ('pwr', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'Log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
