# Generated by Django 3.0.2 on 2020-06-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0038_log_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
