# Generated by Django 3.0.2 on 2020-06-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0016_log'),
        ('memberauth', '0040_auto_20200614_1541'),
    ]

    operations = [
    ]
