# Generated by Django 3.0.2 on 2020-06-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0042_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
