# Generated by Django 3.0.2 on 2020-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberauth', '0043_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthLogtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macaddress', models.CharField(db_column='macAddress', max_length=10)),
                ('gradenumber', models.CharField(db_column='gradeNumber', max_length=15)),
                ('lecture_id', models.CharField(max_length=8)),
                ('one_week', models.IntegerField()),
                ('two_week', models.IntegerField()),
                ('three_week', models.IntegerField()),
                ('four_week', models.IntegerField()),
                ('five_week', models.IntegerField()),
                ('six_week', models.IntegerField()),
                ('seven_week', models.IntegerField()),
                ('eight_week', models.IntegerField()),
                ('nine_week', models.IntegerField()),
                ('ten_week', models.IntegerField()),
                ('eleven_week', models.IntegerField()),
                ('twelve_week', models.IntegerField()),
                ('thirteen_week', models.IntegerField()),
                ('fourteen_week', models.IntegerField()),
                ('fifteen_week', models.IntegerField()),
                ('sixteen_week', models.IntegerField()),
            ],
            options={
                'db_table': 'memberauth_logtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=2)),
                ('grade_number', models.CharField(max_length=10, unique=True)),
                ('mac_address', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'memberauth_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthMemberCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'memberauth_member_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthPromember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade_number', models.CharField(max_length=10, unique=True)),
                ('mac_address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'memberauth_promember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthPromemberCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'memberauth_promember_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=30)),
                ('lecture_room', models.CharField(max_length=7)),
                ('lecture_id', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'memberauth_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberauthSubjectTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=10)),
                ('which_day', models.CharField(max_length=8)),
                ('start_time', models.CharField(max_length=8)),
                ('finish_time', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'memberauth_subject_time',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='logTable',
        ),
        migrations.RemoveField(
            model_name='member_course',
            name='Member_num',
        ),
        migrations.RemoveField(
            model_name='promember_course',
            name='ProMember_num',
        ),
        migrations.RemoveField(
            model_name='subject_time',
            name='Subject_num',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Member_course',
        ),
        migrations.DeleteModel(
            name='ProMember',
        ),
        migrations.DeleteModel(
            name='ProMember_course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subject_time',
        ),
    ]
